In [80]:
import numpy as n
numpy_array = n.arange(1,10,1)

print(numpy_array)

print(numpy_array.shape)

numpy_array *=2
print(numpy_array)

numpy_array +=2
print(numpy_array)

[1 2 3 4 5 6 7 8 9]
(9,)
[ 2  4  6  8 10 12 14 16 18]
[ 4  6  8 10 12 14 16 18 20]


In [55]:
float_array = numpy_array.astype(n.float64)
float_array

array([ 4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [56]:
n.linspace(10,11,50)

array([10.        , 10.02040816, 10.04081633, 10.06122449, 10.08163265,
       10.10204082, 10.12244898, 10.14285714, 10.16326531, 10.18367347,
       10.20408163, 10.2244898 , 10.24489796, 10.26530612, 10.28571429,
       10.30612245, 10.32653061, 10.34693878, 10.36734694, 10.3877551 ,
       10.40816327, 10.42857143, 10.44897959, 10.46938776, 10.48979592,
       10.51020408, 10.53061224, 10.55102041, 10.57142857, 10.59183673,
       10.6122449 , 10.63265306, 10.65306122, 10.67346939, 10.69387755,
       10.71428571, 10.73469388, 10.75510204, 10.7755102 , 10.79591837,
       10.81632653, 10.83673469, 10.85714286, 10.87755102, 10.89795918,
       10.91836735, 10.93877551, 10.95918367, 10.97959184, 11.        ])

In [57]:
n.isnan(numpy_array)

array([False, False, False, False, False, False, False, False, False])

In [58]:
n.ones((4,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [59]:
n.eye(10,dtype=float)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [65]:
array_n = n.arange(1,26)
array_m = array_n.reshape((5,5))
array_m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [69]:
n.random.random(size =(3,2))

array([[0.60734321, 0.41678319],
       [0.09579508, 0.05824492],
       [0.10260265, 0.81618095]])

In [75]:
n.random.randn(9,3)

array([[-0.97036338,  2.03647835, -2.44118279],
       [ 0.0212921 , -0.93945735, -0.29632234],
       [-0.75862468,  0.63103216, -1.94269511],
       [-1.10856568,  0.27502453, -0.21593298],
       [-0.52230801,  0.61273729,  1.10504683],
       [ 1.93356234,  1.93387128,  0.68087319],
       [-0.44246183,  1.01162762, -0.12715507],
       [ 0.4152727 ,  0.15527981, -0.82112806],
       [ 0.07933259, -0.21933981, -2.55797115]])

In [78]:
array_m[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
array_n[::-1]

array([25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1])

In [81]:
array_n>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [82]:
array_m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
array_m.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [85]:
array_n.max()

25

In [86]:
array_n.min()

1